steps:
  run-hello-world:
    image: docker:27
    commands:
      - dockerd &
      - sleep 30
      - docker run hello-world
    backend_options:
      docker:
        runtime: sysbox-runc
when:
  - event: push
    branch: master
