steps:
  run-hello-world:
    image: docker:latest
    commands:
      - dockerd --iptables=true --storage-driver=overlay2 &
      - sleep 30
      - docker run hello-world
    backend_options:
      runtime: sysbox-runc
when:
  - event: push
    branch: master
