steps:
  run-hello-world:
    image: ubuntu
    commands:
      - echo "hello world"
    backend_options:
      docker:
        runtime: sysbox-runc
        hostname: syscont
when:
  - event: push
    branch: master
