steps:
  run-hello-world:
    image: nestybox/ubuntu-jammy-systemd-docker
    commands:
      - dockerd && docker run hello-world
    backend_options:
      runtime: sysbox-runc
when:
  - event: push
    branch: master
