steps:
  run-hello-world:
    image: docker:27
    commands:
      - dockerd --iptables=true &
      - sleep 30
      - docker run hello-world
    backend_options:
      runtime: sysbox-runc
when:
  - event: push
    branch: master
