steps:
  run-hello-world:
    image: nestybox/ubuntu-jammy-systemd:latest
    commands:
      - dockerd &
      - sleep 30
      - docker run hello-world
    backend_options:
      docker:
        runtime: sysbox-runc
        hostname: syscont
when:
  - event: push
    branch: master
